### ISSUE TITLE
Промо-страница

### ISSUE THREAD

**Issue by adubovskoy** [dru-io/promo#1]
В одном из друпал-чатов в очередной раз возникла идея русскоязычной промо-страницы. Мы уже кое-что обсуждали: https://github.com/dru-io/Dru.io/issues/11 . 

В этот раз план следующий: взять кошелек, собрать пожертвования от тех кому хочется такую страницу иметь, и сделать. Можно пока просто статикой. Потом докрутим функционал.

Начать с простой схемы:
1. Собрать тысяч 10-15 (в любом случае вся эта история про благотворительность и общий интерес. Коллаборация деньгами это скорее способ коммуникации, чем действительно необходимость).
2. Отдать проработку дизайна инициативным дизайнерам из друпал-студий (пока хотим клипсайту, после обсуждений в чатике, надеюсь они не откажутся). По пути обсуждая тут в ишью наработки. 
3. Потом сверстать. Положить. Собрать критику, и принимать пул-реквесты на совершенствование.

Деньги тут: http://yasobe.ru/na/drupalpromo  . 7тыс. мы нашли за первые 10 минут обсуждения :) Я отчет потом сделаю. Спорсорам надо будет предусмотреть отдельные "спасибо" в копирайтах (первая мысль -- ссылка на страницу с списком пожертвований, по типу https://vk.com/topic-55614321_29631558 )

**Comment by adubovskoy** [comment]
#2 , #3

**Comment by adubovskoy** [comment]
Структура:

- Почему Drupal хорошая система управления для моего сайта.
- Крупные сайты на Drupal (в т.ч. русскоязычные), скрины
- Друпал для малого бизнеса и "домашних страниц"
- Drupal-сообщество, встречи/эксперты (фото конференций, пару фото офисов компаний типа аквии)
- Где мне получить помощь? Ссылки на dru.io, чаты, публичные блоги.
- Мне нужна помощь (форма, сделаем так что у кого в профиле стоит галочка "получать письма с промо-страницы, будут получать" - на манер битрикса с партнерами).

можно видео i20biz использовать имхо

**Comment by Niklan** [comment]
@adubovskoy хорошая идея. Не думаю что такой сайт  нужно перегружать левой инфой. Максимум фактов в лицо и сразу. А всякие каталоги и прочее уже потом по надобности. Не факт что они вообще нужны на промо сайте то.

**Comment by adubovskoy** [comment]
Первая итерация

![promo 1](https://cloud.githubusercontent.com/assets/297623/26684432/aa9fe966-46ef-11e7-9153-026c6ca1cd77.jpg)

**Comment by politsin** [comment]
Страница "почему друпал", а самого ответа нет.
Давайте сделаем блок основных плюшек, я бы отметил следущие
- Mobile Friendly
- SEO Friendly
- Быстрый - очень быстрый (охренеть как быстрый если d8)
- Безопасный - №1 по безопасности
- Лучший выбор для управления контентом
- Легко интегрируется с 1С, amoCRM, соц.сетями, платежными системами и т.д.
- Множество дополнительных модулей ХХХшт
- Популярный (топ 3 мирового рейтинга) Много разработчиков - вы сможете поменять подрядчика

---------------
что в этот блок точно не стоит складывать (эти плюшки очень круты, но не актуальны нашим задачам) - мультиязычность, мультисайтовость, штучки для программистов - симфони, твиг и тп..

**Comment by politsin** [comment]
Бесплатен,  заменим на **0 руб!** - быстрее восприятие.
Сам друпал стоит 0 рублей, и ХХХХ модулей к нему стоят 0 рублей %-)

**Comment by fortis** [comment]
ну так уж петь дифирамбы имхо не стоит, 0 рублей это перебор

**Comment by fortis** [comment]
и вовсе не звучит как преимущество, особенно если это выпячивать

**Comment by adubovskoy** [comment]
Первый вариант, требуются комментарии )

![drupal-1 4](https://user-images.githubusercontent.com/297623/27380578-50e22ea4-5688-11e7-902d-0f01d2b61ea4.jpg)

**Comment by adubovskoy** [comment]
Благодарности внизу будут заменены на ссылку, где будет список всех кто помогал донатом.

**Comment by Niklan** [comment]
Круто. Могу помочь с версткой и реализацией если потребуется. Могу как с 0 поднять помочь, так и моментами.

**Comment by AntonShloma** [comment]
Не забыть про видос, есть англ версия если что
https://www.youtube.com/watch?v=xF3aECbeC5w

**Comment by Niklan** [comment]
@AntonShloma а там вроде это видео и вставлено в превью.

**Comment by byteval** [comment]
Все нравится, готов поучаствовать, если требуется помощь.
Направленность страницы в первую очередь для клиентов, насколько понимаю. Тогда блок Информационные ресурсы может заменить, т.к. есть сайты с информацией не часто обновляемой, что может отпугнуть.
Интересно бы, наверно, добавить картинки блоки по основным моментам из видео, графики например.

**Comment by adubovskoy** [comment]
Первая часть выполнена, сайт доступен по адресу http://drupal.dru.io , спасибо: http://drupal.dru.io/thanks .
