### ISSUE TITLE
Дру в списке ресурсов

### ISSUE THREAD

**Issue by Alex-Malkov** [dru-io/promo#12]
Привет всем. Отличную промо-страницу сделали, здорово!

Заранее прошу прощения, что вмешиваюсь в вашу инициативу, т.к. не спонсировал её и, как мне кажется, я не имею морального права создавать здесь ишью. Но есть одна проблема.

Я обратил внимание, что в списке Drupal ресурсов есть **Drupal.ru.** 

И так, как в обсуждении, к примеру, по поводу функционала формы Анатолий справедливо [заметил](https://github.com/dru-io/promo/issues/8#issuecomment-305733330), что "...форма будет причиной для многих кампаний не давать ссылку на этот сайт...", то лично для меня наличие Drupal.ru будет основной причиной не ссылаться на промо-страницу. Во всяком случае до тех пор, пока на ресурсе не будет наведён порядок.

Я имею ввиду низкую культуру дру (к примеру [краткий перечень](http://drupal.ru/comment/695220#comment-695220) от @dgastudio), непрозрачность управления и странные публикации в Твиттере - вот, к примеру, последняя https://twitter.com/drupalru/status/889155884374515713 

У меня уже была одна проблема с заказчиком, у которого сложилось негативное впечатление о друпале, как потом выяснилось, после посещения им drupal.ru. Мне дорогого стоило его переубедить в обратном. Ну да ладно - это частный случай, бывает.

В качестве пожелания. 

Обсудите, пожалуйста, между собой - насколько принципиально присутствие ссылки на drupal.ru на промо-странице. Как решите, так и решите. Эта страница ваше детище, вам решать. Я просто поделился своим опасением.

**Comment by adubovskoy** [comment]
По голосованию в чате результат против. Ишью закрываю.
