### ISSUE TITLE
Опечатки на странице благодарностей

### ISSUE THREAD

**Issue by SemanticsPRO** [dru-io/promo#14]
http://drupal.dru.io/thanks

Синица Сергей   Геннадьевич (студия DrupalCoder, г. Краснодар)
Синица Алексей Генадьевич (студия DrupalCoder, г. Краснодар)

Братья, а отчества немного различаются.

**Comment by Niklan** [comment]
Завтра доберусь, поправлю если разберусь что и как)

**Comment by SemanticsPRO** [comment]
Ну или репу залей

**Comment by Niklan** [comment]
@SemanticsPRO я в той разработке пока не участвовал, даже не разу к серверу с сайтом не подключался и не видел что да как. Я думаю пока не буду лить ибо не знаю что там утечь может, а вот затра пару доработок и правок уже сделаю, если никто не поправит, я сам поправлю ошибки.

**Comment by adubovskoy** [comment]
Поправил, спасибо
